INSERT INTO visas VALUES (1, 'FREE', 'Great Britain');
INSERT INTO visas VALUES (2, 'FREE', 'USA');
INSERT INTO visas VALUES (3, 'FREE', 'Thailand');
INSERT INTO visas VALUES (4, 'FREE', 'Canada');

INSERT INTO bank VALUES (1, 0.00);

INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('51', '150', 'Минск', 'Шоп тур в Берлин на БОЛЬШОЕ открытие сезонных распродаж. В начале распродаж большой размерный ряд одежды и обуви. А как известно всем в конце распродаж есть маленький выбор и остаются только самые маленькие или самые большие размеры ПОЭТОМУ мы приглашаем ВСЕХ на НАЧАЛО РАСПРОДАЖ 10.02 и 17.02.2021 когда есть все размеры и большой выбор. В добавок к шопингу Вы посетите 2 увлекательные и интересные экскурсии по Познани и Потсдаму.', 'Берлин', '10/02/2021', '17/02/2021', 'LAST_MINUTE', 'Шоп тур в Берлин', 'SHOPPING');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('52', '90', 'Гродно', 'Шоп тур в Вильнус на БОЛЬШОЕ открытие сезонных распродаж. В начале распродаж большой размерный ряд одежды и обуви. А как известно всем в конце распродаж есть маленький выбор и остаются только самые маленькие или самые большие размеры ПОЭТОМУ мы приглашаем ВСЕХ на НАЧАЛО РАСПРОДАЖ 10.02 и 17.02.2021 когда есть все размеры и большой выбор.', 'Вильнус', '10/02/2021', '17/02/2021', 'LAST_MINUTE', 'Шоп тур в Вильнус', 'SHOPPING');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('53', '65', 'Гродно', 'Шоп тур в Москву на БОЛЬШОЕ открытие сезонных распродаж. В начале распродаж большой размерный ряд одежды и обуви. А как известно всем в конце распродаж есть маленький выбор и остаются только самые маленькие или самые большие размеры ПОЭТОМУ мы приглашаем ВСЕХ на НАЧАЛО РАСПРОДАЖ 10.02 и 17.02.2021 когда есть все размеры и большой выбор.', 'Белосток', '10/02/2021', '17/02/2021', 'NORMAL', 'Шоп тур в Белосток', 'SHOPPING');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('54', '70', 'Гродно', 'Экскурсионный тур в Прагу', 'Прага', '12/02/2021', '18/02/2021', 'LAST_MINUTE', 'Экскурсия в Прагу', 'EXCURSION');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('55', '80', 'Гродно', 'Экскурсионный тур в Белосток', 'Берлин', '10/02/2021', '17/02/2021', 'NORMAL', 'Экскурсия в Берлин', 'EXCURSION');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('56', '120', 'Минск', 'Экскурсионный тур в Санкт-Петербург', 'Санкт-Петербург', '15/02/2021', '22/02/2021', 'NORMAL', 'Санкт-Петербург', 'EXCURSION');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('57', '40', 'Гродно', 'Посетим маёнтак "Каробчыцы", проплывем по Августовскому каналу, увидим памятники средневековой архитектуры, продегустируем Лидское пиво.', 'Лида', '20/02/2021', '20/02/2021', 'NORMAL', 'Экскурсионный тур Лида-Гродно', 'EXCURSION');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('58', '170', 'Гродно', 'Отличная программа! Незабываемая экскурсия по Бресту, посмотрим на замки в Коссово и Ружанах, Брестскую крепость, Беловежскую пущу.', 'Брест', '27/02/2021', '28/02/2021', 'NORMAL', 'Тур в Брест и Беловежскую пущу', 'EXCURSION');
INSERT INTO tours (id, cost, departure, description, destination, end_time, start_time, status_of_the_tour, tour_name, type_of_tour) VALUES ('59', '64', 'Минск', 'В Борисове есть поистине необычное место. А необычным оно считается из-за того, что здесь самым интересным образом воссозданы жизнь, культура и традиции кочевых народов. Здесь речь идёт о монгольских и бурятских юртах. Достаточно необычные сооружения для нашей страны. Это единственное место на территории Беларуси, где вживую можно увидеть, как жили кочевые племена.', 'Брест', '27/02/2021', '28/02/2021', 'NORMAL', 'В гостях у Хаски', 'EXCURSION');
